### ISSUE TITLE
help test husky 0.15 (rc)

### ISSUE THREAD

**Issue by typicode** [typicode/husky#195]
I'm happy to announce Husky `v0.15-beta` (which may become `v1.0` if everything goes fine :))

`v0.15` is a complete rewrite with a new API. Overall `v0.15` code is much simpler, should better support `yarn`, `pnpm` and solve some of the opened issues.

Since it's a rewrite, for safety I'm publishing it under a `beta` tag.

If you give it a try, bug reports and feedbacks would be really appreciated (you can post them here).

`README` for the new version can be found in the [`dev`](https://github.com/typicode/husky/tree/dev) branch and you can install it with `npm install husky@beta --save-dev`. You'll also have to update your `package.json` to add a `husky` field.

Thanks to everyone!

__Note__: it's a __beta__ so there are probably going to be bugs and things that will change before it gets stable. __If you need something stable please keep using `v0.14`__.

**Comment by paulgv** [comment]
Hi,
I'm trying `v0.15.0-beta.10` on OS X 10.12.6.
I've added the following config to my `package.json`:
```json
{
  "husky": {
    "hooks": {
      "pre-commit": "echo \"Hello world\""
    }
  }
}
```
But the hook isn't triggered when I commit files.

**Comment by statianzo** [comment]
Is the plan to remove nested directory support permanently?
https://github.com/typicode/husky/blob/dev/src/installer/index.ts#L121

My team's about to adopt husky, but it won't work for us without nesting support. Adding a package.json and running npm install in the root isn't an option because we don't own it.

Is there a way I could help out with bringing the feature back?

**Comment by typicode** [comment]
@paulgv thanks for the report and the details! I'll try to reproduce.

How was Node installed (nvm, brew, ...)?
Where are you running git command from (GUI client like GitHub desktop, terminal, Atom, ...)?
Do you have this https://github.com/typicode/husky/blob/dev/templates/hook.sh in `.git/hooks/pre-commit`?

**Comment by paulgv** [comment]
Hi @typicode 
I was able to make it work thanks to your questions :)
Looks like the hooks in `.git/hooks/` where stuck on husky 0.14, I removed all the hooks and reinstalled husky and now it works like a charm!

For reference, here's the info you asked:
I'm running Git via the CLI (iTerm 2 & oh-my-zsh).
Node was installed with NVM.

```sh
$ which node
/Users/paul/.nvm/versions/node/v8.6.0/bin/node
```

Here's the contents of `.git/hooks/pre-commit` prior to removing all the hooks and reinstalling husky:
```
#!/bin/sh
#husky 0.14.3

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}

cd "."

# Check if precommit script is defined, skip if not
has_hook_script precommit || exit 0

load_nvm () {
  # If nvm is not loaded, load it
  command_exists nvm || {
    export NVM_DIR=/Users/paul/.nvm
    [ -s "$1/nvm.sh" ] && . "$1/nvm.sh"
  }

  # If nvm has been loaded correctly, use project .nvmrc
  command_exists nvm && [ -f .nvmrc ] && nvm use
}

# Add common path where Node can be found
# Brew standard installation path /usr/local/bin
# Node standard installation path /usr/local
export PATH="$PATH:/usr/local/bin:/usr/local"

# nvm path with standard installation
load_nvm /Users/paul/.nvm

# nvm path installed with Brew
load_nvm /usr/local/opt/nvm

# Check that npm exists
command_exists npm || {
  echo >&2 "husky > can't find npm in PATH, skipping precommit script in package.json"
  exit 0
}

# Export Git hook params
export GIT_PARAMS="$*"

# Run npm script
echo "husky > npm run -s precommit (node `node -v`)"
echo

npm run -s precommit || {
  echo
  echo "husky > pre-commit hook failed (add --no-verify to bypass)"
  exit 1
}
```

**Comment by vincecoppola** [comment]
We're using `husky@beta` and so far it's been great—much faster! The only feedback I currently have is regarding the new top-level `husky` key that's required within `package.json`. We'd much prefer using a standard `.*rc` config file.

@typicode I've created #209 in hopes that you guys might also find this flexibility useful for the upcoming version that's in the works.

**Comment by TinOo512** [comment]
```

**Comment by lyyourc** [comment]
@typicode  Failed in Jenkins, a duplicate of #79

**Comment by leggomuhgreggo** [comment]
I might also be having an NVM issue. 

Having an installation error when I run `yarn add -D husky@next`

```
error /Users/username/projects/my-project/node_modules/husky: Command failed.
Exit code: 1
Command: node lib/installer/bin install
Arguments:
```

```
$sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.2
BuildVersion:   17C205
$ which node
/Users/username/.nvm/versions/node/v9.1.0/bin/node
 $ node -v
v9.1.0
$ npm -v
5.5.1
```
 
Tried with and without a husky config in my `package.json` and for giggles deleted and readded `.git/hooks`

Let me know if there's anything further I can offer by way of debugging information. Thanks!

**Comment by typicode** [comment]
@leggomuhgreggo could you retry with the current `husky@next` version ? I've fixed an error when installing.

**Comment by leggomuhgreggo** [comment]
That did it. Works like a charm now. Many thanks for the speedy attention 👍

**Comment by markgoho-EDT** [comment]
![image](https://user-images.githubusercontent.com/33099374/35422483-e94e21a4-0216-11e8-99b8-fd90e1ba25b7.png)

Getting this on pre-commit and pre-push actions

**Comment by typicode** [comment]
@markgoho-EDT Thanks for the feedback, What's your OS and how did you install Node?
Hmm the GitHub Desktop message is strange as it seems to say that there's no `pre-push` file.
What's the content of `.git/hooks/pre-push`?

**Comment by markgoho-EDT** [comment]
@typicode here's the pre-push file

``` bash
#!/bin/bash
# husky
# v0.15.0-rc.3

hookname=`basename "$0"`
[ -f package.json ] && cat package.json | grep -q "\"$hookname\"[[:space:]]*:"

export GIT_PARAMS="$*"

if [[ $? -eq 0 ]]; then
  node_modules/husky/node_modules/.bin/run-node ./node_modules/husky/lib/runner/bin $hookname
  exit $?
fi
```

**Comment by Falieson** [comment]
with `v0.15.0-rc.3` I can't install... https://github.com/typicode/husky/issues/229

**Comment by typicode** [comment]
@markgoho-EDT thanks, the main cause was identified here https://github.com/typicode/husky/issues/228 a fix will be published.

**Comment by typicode** [comment]
@travi thanks for the report, can you try with `v0.15.0-rc.4`, it should just display the `git` error message but shouldn't fail.

**Comment by typicode** [comment]
@markgoho-EDT could you retry with `v0.15.0-rc.5`? It should fix the issue.

**Comment by travi** [comment]
> can you try with v0.15.0-rc.4

looks like that took care of it

> it should just display the git error message but shouldn't fail.

i do still see the error in the logs, like you mentioned, but it does not fail:

```
       husky > failed to install
       Command failed: git rev-parse --git-dir
       fatal: Not a git repository (or any parent up to mount point /tmp)
       Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

https://travis-ci.org/travi/greenkeeper-keeper/jobs/337779201#L2126-L2129

thanks!

**Comment by simon360** [comment]
One comment on versioning: a lot of projects will have `"husky": "^0.14.3"` in their `package.json`. If this gets released as `0.15`, anyone who isn't using a lockfile (or updates their lockfile) will get a breaking release.

In the interest of sticking to semver, I'm of the opinion that this should be released as `1.0.0`, regardless of whether or not it's considered perfectly stable.

**Comment by jthegedus** [comment]
As our tooling works against us with semver and pre `1.x.x`, as stated by @simon360 , I agree with them. However, I just looked it up and the [semver spec](https://semver.org/#spec-item-4) states otherwise

>Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I guess we just need to do our due diligence before upgrading.

**Comment by simon360** [comment]
Huh, interesting @jthegedus - though, it makes sense, given that `react` took advantage of the pre-`1.0.0` behaviour for a while.

For example, if you enter `^0.13.0` on https://semver.npmjs.com/ with the `react` package, it won't automatically bump you to `0.14.8`, but if you used `^15.0.0`, you'd get bumped up to `15.6.2`.

Basically, I was wrong, so you can ignore me. Hopefully I'm not the only one who's learned something new about semver here, though.

**Comment by typicode** [comment]
> Hopefully I'm not the only one who's learned something new about semver here, though.

Thanks for sharing and that's a good point about semver 👍 

Some words about why it's `v0.15.0-...` instead of `v1.0.0-...`, I wanted to rewrite husky and wasn't sure if the new version would be viable or not. So to be on the safe side, I just bumped minor, and if it wasn't viable, I would just have continued with `v0.14.3` and maybe jumped to `v0.16.0`.

That said, as I'm getting feedbacks and fixing the small bugs in `v0.15.0`, I'm thinking about making it directly `v1.0.0` when it'll be ready to avoid confusions with `v0.14.3`.

Also, if you have your hooks in `scripts` (old way) rather than `husky.hooks`  (new way), husky will still run them but will show a deprecation message :)

**Comment by fernandopasik** [comment]
Hi @typicode, is it much far the final release of 0.15 ? Thanks for the hard work!!

**Comment by einavk** [comment]
Hi,
I tried moving from husky stable version to the rc9 version.
When I did, it did not install me the hooks properly.
Turn out the issue is this:
Expecting package.json to be at the same level as .git, skipping Git hooks installation.
My project has .git on the parent directory, and this cannot be changed.
Why is this expectation set? 
Can this be overridden somehow?
Thanks

**Comment by voxpelli** [comment]
@typicode Maybe add a GitHub milestone that tracks the 1.0/0.15 release so that we all can look at and maybe help out triaging any reported bugs? 🙂

**Comment by typicode** [comment]
@einavk it enforces having a single source truth, more details here https://github.com/typicode/husky/issues/272. 

There are workarounds described here:
https://github.com/typicode/husky/blob/dev/docs.md

But I'm reconsidering this behaviour (and it's one of the last blocker for `v1.0` I guess).

@voxpelli that's a good suggestion :) I've never used GitHub Milestones though, will need to read docs.

**Comment by typicode** [comment]
I'm going to close this issue as `1.0.0`  is being released 🎉🎉🎉 (`1.0.0-rc.15` is already the `@latest` version) 

Thanks to everyone who have participated in this issue: @paulgv @statianzo @vinsidious @TinOo512 @lyyourc @leggomuhgreggo @markgoho-EDT @travi @Falieson @simon360 @jthegedus @fernandopasik @einavk @sandangel @voxpelli 🙏 !
