### ISSUE TITLE
package.json in subdirectory case

### ISSUE THREAD

**Issue by a-x-** [typicode/husky#452]
we have complex project with frontend subdirectory
can husky use `git rev-parse --show-toplevel` to find out repo root and .git in it?
can husk allow debug process?
what happens if .git has not found?

**Comment by a-x-** [comment]
I found similar issue: https://github.com/typicode/husky/issues/7

And I found some logs currently: 
```
husky > setting up git hooks
husky > failed to install
EISDIR: illegal operation on a directory, read
```

**Comment by a-x-** [comment]
`frontend/projects/admin/package.json`:
```json
{
  "devDependencies": {
    "husky": "^1.3.1",
  },
  "husky": {
    "hooks": {
      "pre-commit": "scripts/precommit-lint"
    }
  },
  ...
}
```
also, I have: `frontend/projects/admin/scripts/precommit-lint`

**Comment by a-x-** [comment]
I look into your src and I understands now, all should work as I want, but...

**Comment by a-x-** [comment]
I did some debugging session

on line
`const userPkgDir = pkgDir.sync(path.join(huskyDir, '..'));`
`userPkgDir` is incorrect (`/Users/....../frontend/projects/admin/node_modules` for me)

what if you add second `..`?
how can it work usually?

**Comment by a-x-** [comment]
everything is working After adding ../.. instead of .. !

**Comment by typicode** [comment]
Hi @a-x-,

Thanks for the details and PR.

Do you have a `package.json` in `/Users/....../frontend/projects/admin/node_modules`?

**Comment by typicode** [comment]
Not sure, but I think that package managers like `pnpm` have a different directory structure, so using `../..` may not work in every cases actually.

Could you try with https://www.npmjs.com/package/find-pkg? Does it ignore directories named `package.json` (https://github.com/typicode/husky/issues/450)

**Comment by a-x-** [comment]
> Do you have a `package.json` directory in frontend/projects/admin/node_modules

no, package.json is versioning file. node_modules must be ignored by git.
package.json, afaik, always placed in project root.

**Comment by a-x-** [comment]
Wow

ls node_modules/package.json
LICENSE		README.md	lib		package.json

https://github.com/IonicaBizau/pkg.json

We have to filter out directories...

**Comment by a-x-** [comment]
I created https://github.com/jonschlinkert/find-pkg/issues/1 issue

**Comment by typicode** [comment]
I think it should work now with `2.5.0` (would need some testing)

**Comment by Dufgui** [comment]
Sorry but not yet:
```
$ git commit -m "Husky test commit"
husky > pre-commit (node v10.15.1)
Current directory is not a git directory!
husky > pre-commit hook failed (add --no-verify to bypass)
```

my folder structure is:
```
  project/
    .git/
    releng/
    ci/
    modules/frontend/
      # frontend files and folders generate with jhipster ...
      package.json
```

I try upgrade husky form 2.4.0 to 2.5.0 but the bug is still the same. I downgrade to 1.3.1 and it's not working too. 

I uninstall husky and my commit works

**Comment by typicode** [comment]
@Dufgui can you retry with `v3.0.0`? As suggested, it now uses `git rev-parse` to find git directory.

```
HUSKY_DEBUG=1 npm install husky@3.0.0 --save-dev
```

**Comment by miajhaochen** [comment]
> @Dufgui can you retry with `v3.0.0`? As suggested, it now uses `git rev-parse` to find git directory.
> 
> ```
> HUSKY_DEBUG=1 npm install husky@3.0.0 --save-dev
> ```

With `v3.0.0`, it works pretty fine for me now.

**Comment by typicode** [comment]
Closing as it seems to be working now based on @miajhaochen. Feel to create another isssue if needed.
