### ISSUE TITLE
override dir in package.json

### ISSUE THREAD

**Issue by cztomsik** [typicode/husky#7]
Some projects hold `package.json` in subdirectory rather than in root.

In such case, husky will report `can't find .git/hooks/`

This could be easily solved if husky was able to read `package.json` and look up for specific property like `gitDir` or so.

**Comment by conord33** [comment]
I am running into the same issue as cztomsik.
The workaround above doesn't work because husky doesnt know where precommit is.  So it will never run the cd command to get to the correct directory.  The directory needs to be set before husky checks `npm run --json` for the hooks.

I can fix this manually by updating the husky hook scripts but it is obviously not ideal.

Would be cool if husky automatically did this by calling the githook script in the directory of the package.json that installed it.

**Comment by typicode** [comment]
Just for the record, fixed in v0.7.0, thanks to @conord33 PR

**Comment by dmi3y** [comment]
I can't get it working. Do I have to set up something specifically or give it some options?

For refs here is the PR mentioned above:
https://github.com/typicode/husky/pull/17

My details:
OSX El Capitan
husky@0.11.5
npm: '3.10.3'
node: '6.3.0'

Thanks!

**Comment by rakhmatullov** [comment]
I still have the same problem. I have .git folder in upper folder than package.json and node_modules and I and npm precommit doesn't search parent folders for .git/hooks.

**Comment by MartinMuzatko** [comment]
It would be nice to have a setting for this @typicode

**Comment by goramm** [comment]
It works for me. This is my setup:

**project**
`yarn add --dev husky`

**project/package.json**
<pre>{
  "devDependencies": {
    "husky": "^0.14.3"
  },
  "scripts": {
    "precommit": "yarn lint && yarn test",
    "prepush": "yarn lint && yarn test",
    "lint": "cd subproject && yarn lint",
    "test": "cd subproject && yarn test"
  }
}</pre>

**subproject/package.json**
<pre>
"scripts": {
    "postinstall": "cd .. && yarn install",
    "test": "jest",
    "lint": "tslint -c tslint.json 'src/**/*.ts' --type-check --project tsconfig.json"
  }
</pre>

**Comment by AlexWang-16** [comment]
Thanks for posting this solution @goramm. I'm building a docker file for my project and I'm running into this issue as well. 

The problem I have is that I can't put husky 1 directory above. I have a project directory separated by "client" sub-folder and "server" sub-folder each with its individual package.json file. Is there a workaround such that I can reference the .git folder in the root directory?

I tried to use symbolic linking but Docker complains that the path is outside of the build context and stops the build process.
