### ISSUE TITLE
Husky 4.x HUSKY_GIT_PARAMS behaviour changed from 3.x (post-checkout)

### ISSUE THREAD

**Issue by wuppious** [typicode/husky#700]
In Husky version 4.2.3 `HUSKY_GIT_PARAMS` are somehow differrent from 3.1.0 atleast in `post-checkout` hook.

OS: archlinux
Shell: fish
Node: v13.12.0

`"post-checkout": "./git-hooks/post-checkout.sh $HUSKY_GIT_PARAMS"`

```
./git-hooks/post-checkout.sh
----------------------------
#!/bin/bash


echo $1
echo $2
echo $3
```

**Husky 3.1.0**
```
➜ git checkout
Your branch is up to date with 'origin/feature/some-branch'.
husky > post-checkout (node v13.12.0)
de533c22279046fe020c9604e607d39a70e9c39d
de533c22279046fe020c9604e607d39a70e9c39d
1
➜
```

**Husky 4.2.3**
```
➜ git checkout
Your branch is up to date with 'origin/feature/some-branch'.
husky > post-checkout (node v13.12.0)
de533c22279046fe020c9604e607d39a70e9c39d de533c22279046fe020c9604e607d39a70e9c39d 1


➜
```

Seems that the variable is not correctly expanded to the arguments in Husky 4.2.3
Considering it works in 3.1.0, I don't believe it's a problem of my shell. The variable is seemingly the same in both versions, so I'm not sure what is up.

**Comment by amjmhs** [comment]
Same here. I have a prepare-commit-msg with a javascript-file that should do something based on the HUSKY_GIT_PARAMS. But instead of getting something like:
```
[.git/COMMIT_EDITMSG, message] or 
[.git/COMMIT_EDITMSG, template] or 
[.git/COMMIT_EDITMSG, commit, HEAD]
```
we always get
```
.git/COMMIT_EDITMSG
```
from `process.env['HUSKY_GIT_PARAMS']`.

**Comment by amjmhs** [comment]
Okay, I looked at the code and compared it to version 3.x
I found [Line 13 at the husky.sh](https://github.com/typicode/husky/blob/cbacd2e85c4cbdbf0632997e9c771eabcea40456/sh/husky.sh#L13) to be the reason for the incorrect expansion of the arguments.

After npx take over the command and execute it with `husky-run.cmd` (at least at my windows machine) it will look like this:
```
"node"  "C:\path\to\node_modules\.bin\\..\husky\bin\run.js" prepare-commit-msg .git/COMMIT_EDITMSG template
```
So the parameters to the `run.js` are this hookname and each git-argument. But there the git-arguments should be quotes to be correctly extracted by `run.js`.

So when I change Line 13 of husky.sh to `"$@" husky-run $hookName \"$gitParams\"` the command from npx will be this:
```
"node"  "C:\path\to\node_modules\.bin\\..\husky\bin\run.js" prepare-commit-msg ".git/COMMIT_EDITMSG template"
```

@wuppious can you verify this by changing the according line at `.git/hooks/husky.sh` ?

**Comment by typicode** [comment]
I've just released a new version (`4.2.5`) which ensures that the shell used is `sh` (`3.x` behaviour). May be worth trying.

**Comment by wuppious** [comment]
> I've just released a new version (`4.2.5`) which ensures that the shell used is `sh` (`3.x` behaviour). May be worth trying.

Seems to work as expected, thank you.

**Comment by amjmhs** [comment]
@typicode this is still not working for me.

_package.json:_
```
"husky": {
  "hooks": {
    "prepare-commit-msg": "node bin/prepare-commit-msg/git-commit-template.js"
  }
}
```

_git-commit-template.js:_
```
const gitParams = process.env['HUSKY_GIT_PARAMS'].split(' ');
console.log(gitParams);
```
Output is always `[ '.git/COMMIT_EDITMSG' ]`, regardless if the git command was `git commit` or `git commit --amend` or `git commit -m "foobar"`.
