### ISSUE TITLE
'husky install' fails if '.git' directory does not exists

### ISSUE THREAD

**Issue by mondeja** [typicode/husky#851]
I have a `postinstall` script in a NPM package:

```json
"postinstall": "is-ci || husky install",
```

If I download the repository using Github UI (Code -> Download ZIP), after extracting it, executing `npm install` raises `Error: .git can't be found`:

<details>
  <summary>postinstall error</summary>

```
> simple-icons-font@4.9.0 postinstall /.../simple-icons-font-develop
> is-ci || husky install

/.../simple-icons-font-develop/node_modules/husky/lib/commands/install.js:20
        throw new Error(".git can't be found");
        ^

Error: .git can't be found
    at Object.install (/.../simple-icons-font-develop/node_modules/husky/lib/commands/install.js:20:15)
    at Object.<anonymous> (/.../simple-icons-font-develop/node_modules/husky/lib/bin.js:43:19)
```

</details>

I can prevent the error doing something like this:

```json
"postinstall": "node -e \"if(require('fs').existsSync('.git')){process.exit(1)}\" || is-ci || husky install",
```

But it seems a bit hacky. What would be the recommended way to solve this?

**Comment by typicode** [comment]
Hi @mondeja,

Thanks for the report. It's fixed in `v5.0.9`. If not in a git repo, Git will simply output a message and not fail.

**Comment by mondeja** [comment]
Thank you @typicode! :pray:

**Comment by gajus** [comment]
This is still an issue:

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/gajus/Documents/dev/gajus/roarr/node_modules/fast-printf
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! /Users/gajus/Documents/dev/gajus/roarr/node_modules/husky/lib/commands/install.js:20
npm ERR!         throw new Error(".git can't be found");
npm ERR!         ^
npm ERR!
npm ERR! Error: .git can't be found
npm ERR!     at Object.install (/Users/gajus/Documents/dev/gajus/roarr/node_modules/husky/lib/commands/install.js:20:15)
npm ERR!     at Object.<anonymous> (/Users/gajus/Documents/dev/gajus/roarr/node_modules/husky/lib/bin.js:43:19)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1102:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:967:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:807:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
npm ERR!     at node:internal/main/run_main_module:17:47

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gajus/.npm/_logs/2021-02-08T20_02_58_259Z-debug.log

```

https://github.com/gajus/fast-printf/blob/master/package.json#L32

**Comment by lc-leoniefarmer** [comment]
I'm running v5.0.9 and am getting this error :-(

` throw new Error(".git can't be found");`

**Comment by typicode** [comment]
Here's how I'm testing:

```
$ cd /tmp
$ mkdir foo && cd foo
$ npm init -y
$ npm install husky -D
$ npx husky install
husky - not a Git repository, skipping hooks installation
```

Is your `package.json` in a nested directory compared to `.git`? If that's the case, see https://typicode.github.io/husky/#/?id=custom-directory

Otherwise could you provide minimal steps for me to reproduce (or a repo)?

**Comment by lc-leoniefarmer** [comment]
We get the issue when we use a repo as a dependency. e.g. in package.json:
`"ourapp": "git+ssh://git@github.com/myproject/ourapp.git#v9.1.3",`

For more information on how this works see: https://docs.npmjs.com/cli/v6/commands/npm-install
<img width="674" alt="Screen Shot 2021-02-11 at 1 06 48 PM" src="https://user-images.githubusercontent.com/31267294/107590432-f48bc300-6c6c-11eb-9c25-8abea2f6f266.png">


We have followed the advice to use pinst to work around this issue:

```
"scripts": {
    "postinstall": "husky install",
    "prepublishOnly": "pinst --disable",
    "postpublish": "pinst --enable"
  }
```

But get the error when installing the updated version:

`throw new Error(".git can't be found");`

**Comment by typicode** [comment]
Thanks for the details. This is a bit of an edge case.

When you publish a package on npm, `prepublishOnly` ensures that `postinstall` is deactivated by renaming it to `_postinstall`. This way, when someone install this package, husky won't install hooks.

Here, this step is not run and when `npm install git+ssh://git@github.com/myproject/ourapp.git#v9.1.3` runs, `postinstall` will execute.

AFAIK I don't think there's a way to detect that.

Personally, I would remove `postinstall`, `prepublishOnly`, `postpublish` and add a mention in the README telling people to manually run `npx --no-install husky install` if they want to enable Git hooks.

**Comment by IevgeniiK-AVISPL** [comment]
Having the same issue...

Trying to install via npm swagger-ui-react ([swagger link](https://www.npmjs.com/package/swagger-ui-react)) BUT im getting this error..
` - swagger-client@3.13.0 postinstall /front/node_modules/swagger-client`
` - husky install`
`throw new Error(".git can't be found");`

as a devDependency husky installed..
`"husky": "^5.0.9",`


if there is an option to fix that?

**Comment by typicode** [comment]
@IevgeniiK-AVISPL seems to be fixed by `swagger-client@3.13.1`

**Comment by LinnJS** [comment]
I am having this same issue when trying to install husky on a repo where I have multiple projects and the .git file is up a directory. Are there configuration options for this use case? I have two projects with node modules nested inside one git repo for the sanity CMS and the Gatsby FE.

![image](https://user-images.githubusercontent.com/23741323/109399297-07aabe00-7910-11eb-81a3-4a8f37383d92.png)

**Comment by naishe** [comment]
Still getting this error with `husky@5.1.3`

```bash
$ husky install
/Users/naishe/dev/project7/this_dir_has_dot_git_file/ui/node_modules/husky/lib/commands/install.js:20
        throw new Error(".git can't be found");
        ^

Error: .git can't be found
```

**Comment by typicode** [comment]
@LinnJS see https://typicode.github.io/husky/#/?id=custom-directory and if it's a monorepo https://typicode.github.io/husky/#/?id=monorepo

**Comment by jes708** [comment]
I experienced the same issue, but was able to resolve it by converting my `postinstall` script to `prepare` instead.

**Comment by Polyhistor** [comment]
Is there any updates on this matter ?

**Comment by cutterbl** [comment]
Here's where I'm having a problem with this. Say I have a 'core' package, using v6 husky setup. The 'core' package includes 'packageA' and 'packageB', also using the v6 husky setup. I get the error when installing an update of 'packageA' or 'B' into 'core', referencing their 'prepare'.

**Comment by bennett-slalom** [comment]
Hi - I'm currently getting this same issue with a `prepare: husky install` npm script throwing the .git not found error when trying to run `sam build` - because the sam cli runs npm i in the container but the container doesn't have a .git. Adding mondeja's original hack works, but it is pretty hacky.

**Comment by DylanCulfogienis** [comment]
Also running into this problem- I think there may have a regression in v6. Also using mondeja's hack.

**Comment by Expensiveee** [comment]
> Hi @mondeja,
> 
> Thanks for the report. It's fixed in `v5.0.9`. If not in a git repo, Git will simply output a message and not fail.

Hi I have the same problem in v6 :/

**Comment by dylanesque** [comment]
I'm also having this issue, granted, the codebase I'm trying to install this to is a frontend that's a folder inside the main repo.

**Comment by zaneclaes** [comment]
@dylanesque that use-case is [well-documented](https://typicode.github.io/husky/#/?id=custom-directory). Tested & working well for me.

**Comment by dylanesque** [comment]
> @dylanesque that use-case is [documented on the project homepage itself](https://typicode.github.io/husky/#/?id=custom-directory). Tested & working well for me.

I can see that, but the error is preventing the installation of the husky package in the first place, so that workaround doesn't help me with that.

**Comment by zaneclaes** [comment]
> I can see that, but the error is preventing the installation of the husky package in the first place, so that workaround doesn't help me with that.

I came to this issue because of the same problem, and those instructions fixed it for me. Specifically, you have to add the modified version of the `prepare` script **before installing husky**, so that the Husky install knows where to put the files (which is what causes this issue).

I just did it on a second project, where the frontend is in `App`. Here were the exact steps:

- Edit `App/package.json` to include `husky` as a devDependency
- Add the prepare script: `cd .. && husky install App/.husky`
- Run `yarn install`

<img width="897" alt="Screen Shot 2021-06-10 at 11 52 52 AM" src="https://user-images.githubusercontent.com/2084821/121573348-689f6300-c9e2-11eb-8329-555c70e4f257.png">

**Comment by muuki88** [comment]
I have this issue as well, but in a different flavor. `stylelint` has a `prepare` step that runs `husky install`.
I receive this error, when running `npm exec --workspaces npm install` to run install on all my workspaces that use `stylelint`.

The _very_ strange part is that this only happens on my machine and we haven't figured out why the hell that is.

**Comment by iamayushdas** [comment]
<img width="904" alt="image" src="https://user-images.githubusercontent.com/40708551/123465891-52adb700-d60c-11eb-9f5d-6a0ee9d867b7.png">

please help!

**Comment by alex-all3dp** [comment]
I am seeing the same issue with v7.0.0 when trying to execute `husky install` in a Docker container. Is there maybe a possible regression?

<img width="422" alt="Bildschirmfoto 2021-07-06 um 09 08 52" src="https://user-images.githubusercontent.com/52403795/124557428-ca17ed80-de39-11eb-9131-6977dcea20e0.png">

**Comment by frarillotta** [comment]
Getting the same error with v7.0.0 when running in a docker container - .git and package.json are definitely in the same folder

![image](https://user-images.githubusercontent.com/44701793/124582796-a44b1280-de52-11eb-88e1-5843889f0152.png)

**Comment by daniilsolovey** [comment]
Same problem:  '.git can't be found'

**Comment by frarillotta** [comment]
Upgrading to 7.0.1 as suggested in https://github.com/typicode/husky/issues/1003#issuecomment-874667232 worked for me!

**Comment by alex-all3dp** [comment]
Works with 7.0.1 for me as well, thank you!

**Comment by deepakthankachan** [comment]
@typicode having the same issue with npm 7 (npm 6 is alright)

**Comment by nthornton2010** [comment]
I'm running 7.0.4 and this issue is happening for me.

**Comment by tomaszdudek7** [comment]
Hitting this issue in `7.0.2`

**Comment by sebmellen** [comment]
Having the same issue in `7.0.2`.

**Comment by Nicolascoding27** [comment]
Having the same issue in 7.0.1

**Comment by BricePissard** [comment]
The bug still exists in `7.04`, could you please place a recursive test to check if the `.git` folder exists in the parent, then parent's parent, then parent's parent's parent... folder.

In the real world, it happens that the GIT is a mono-repo that contains differents folders with different projects with a package.json in each.

**Comment by jackvhall** [comment]
This is still an error. My `.git` and `package.json` are at the same level.

**Comment by OleksiiAbramov** [comment]
Any updates on this? For `8.x` fails if `.git` folder is in the parent directory

**Comment by davidecusato** [comment]
Any update about this ? I have the same behaviour with husky 7.0.0. Thanks
<img width="1337" alt="Screenshot 2022-06-09 at 09 16 26" src="https://user-images.githubusercontent.com/74605769/172788225-0816dfc9-3dfc-4e76-b81f-a1e3750dd8ee.png">

**Comment by samuelaj1** [comment]
The case you may be in is if your package.json file and .git directory are not at the same level. For example, project/.git and project/front/package.json.

By design, husky install must be run in the same directory as .git, but you can change directory during prepare script and pass a subdirectory:

Change script in package.json to this:
// package.json
{
  "scripts": {
    "prepare": "cd .. && husky install front/.husky"
  }
}

Then do npm install to fix it

**Comment by samuelaj1** [comment]
@mondeja try this..

**Comment by mondeja** [comment]
Please, stop mention me in this issue. It was fixed 3 major versions ago and I've not experienced it more.

**Comment by sandeeprajbhar1985** [comment]
> Are there any updates on this? I have the same behavior. husky 7.0.0 with package.json and .git at the same level. I also tried without husky (removing "prepare": "husky install" from scripts) but same problem. Thanks <img alt="Screenshot 2022-06-09 at 09 16 26" width="1337" src="https://user-images.githubusercontent.com/74605769/172788225-0816dfc9-3dfc-4e76-b81f-a1e3750dd8ee.png">

I am facing the same issue

**Comment by sandeeprajbhar1985** [comment]
> Are there any updates on this? I have the same behavior. husky 7.0.0 with package.json and .git at the same level. I also tried without husky (removing "prepare": "husky install" from scripts) but same problem. Thanks <img alt="Screenshot 2022-06-09 at 09 16 26" width="1337" src="https://user-images.githubusercontent.com/74605769/172788225-0816dfc9-3dfc-4e76-b81f-a1e3750dd8ee.png">

I have solved the issue. Steps mentioned below, 

1) delete .git folder from your home directory in my case it is users/sandeeprajbhar/.git 
2) then run :  npx husky-init && yarn

**Comment by Terkea** [comment]
```json
"prepare": "cd .. && husky installtemplate/.husky",
```
this worked for me

**Comment by daninaydenow** [comment]
I'm experiencing common issue with husky 8.0.1 where .git folder and package.json are on the same lvl, but in the end I get : 
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c husky install
npm ERR! husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)

**Comment by pierrebiver** [comment]
You can do `HUSKY=0 yourCommand`   and it should work.

**Comment by khamui** [comment]
> > Are there any updates on this? I have the same behavior. husky 7.0.0 with package.json and .git at the same level. I also tried without husky (removing "prepare": "husky install" from scripts) but same problem. Thanks <img alt="Screenshot 2022-06-09 at 09 16 26" width="1337" src="https://user-images.githubusercontent.com/74605769/172788225-0816dfc9-3dfc-4e76-b81f-a1e3750dd8ee.png">
> 
> I have solved the issue. Steps mentioned below,
> 
> 1. delete .git folder from your home directory in my case it is users/sandeeprajbhar/.git
> 2. then run :  npx husky-init && yarn

So for me the first step worked (i renamed it rather than deleted it). Is there a solution where i can keep my home directory as a git repo? E.g. `/users/myNickname/.git` but also having `/users/myNickname/repos/aProject/.git` working with husky?

**Comment by KhizerRehan** [comment]
> The case you may be in is if your package.json file and .git directory are not at the same level. For example, project/.git and project/front/package.json.
> 
> By design, husky install must be run in the same directory as .git, but you can change directory during prepare script and pass a subdirectory:
> 
> Change script in package.json to this: // package.json { "scripts": { "prepare": "cd .. && husky install front/.husky" } }
> 
> Then do npm install to fix it

Thanks it worked

**Comment by bdovh** [comment]
I have the same problem in version ^7.0.4

Should I try this workaround

```
The case you may be in is if your package.json file and .git directory are not at the same level. For example, project/.git and project/front/package.json.

By design, husky install must be run in the same directory as .git, but you can change directory during prepare script and pass a subdirectory:

Change script in package.json to this: // package.json { "scripts": { "prepare": "cd .. && husky install front/.husky" } }

Then do npm install to fix it

Thanks it worked
```
?

**Comment by totfront** [comment]
@typicode the issue is still there

Here are my steps:
1. `npm i husky` Install Husky 8.0.0
2. `npm run husky install`

Error:
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/42805085/213414167-a9f9adc1-cbd1-49f0-9ecd-ea3a806fc914.png">

Temporary working solution:
1. Go to the directory with `.git` file with `cd ..`
2. From there cast `husky install <YOUR_PATH>/.husky`
or just do the same but in `prepare` script which is @Terkea suggested

**Comment by ZhangHanwen96** [comment]
> 

if you are encountering error when adding some githook like `npx husky add .husky/pre-commit "npm run test"`,  add `cd <your sub folder>` before `npm run test`

**Comment by terwer** [comment]
Still not work, can I skip in CI?Not found a option to skip in ci.
I DO NOT need it in ci

**Comment by terwer** [comment]
Finally ,I found the error is.
I have a nonorepo, root project has a cmd,and sub peoject also.
My ·.husky· is in the root,so I delete the sub project scripts.After that, it works

https://github.com/terwer/zhi/pull/176/commits/c22bd26820215b975193af0cacd8011338caba98

**Comment by TechSaq** [comment]
> > Are there any updates on this? I have the same behavior. husky 7.0.0 with package.json and .git at the same level. I also tried without husky (removing "prepare": "husky install" from scripts) but same problem. Thanks <img alt="Screenshot 2022-06-09 at 09 16 26" width="1337" src="https://user-images.githubusercontent.com/74605769/172788225-0816dfc9-3dfc-4e76-b81f-a1e3750dd8ee.png">
> 
> I have solved the issue. Steps mentioned below,
> 
> 1. delete .git folder from your home directory in my case it is users/sandeeprajbhar/.git
> 2. then run :  npx husky-init && yarn

You saved my day.

**Comment by skolsuper** [comment]
> Thanks for the details. This is a bit of an edge case.
> 
> When you publish a package on npm, `prepublishOnly` ensures that `postinstall` is deactivated by renaming it to `_postinstall`. This way, when someone install this package, husky won't install hooks.
> 
> Here, this step is not run and when `npm install git+ssh://git@github.com/myproject/ourapp.git#v9.1.3` runs, `postinstall` will execute.
> 
> AFAIK I don't think there's a way to detect that.
> 
> Personally, I would remove `postinstall`, `prepublishOnly`, `postpublish` and add a mention in the README telling people to manually run `npx --no-install husky install` if they want to enable Git hooks.

What is the recommendation if you don't control the repo you're installing?

with the following dependency in package.json:

```
"lifion-kinesis": "lifion/lifion-kinesis#e226a505be7506f02e922e103a61bc010673ef09",
```

I still cannot install even when trying to disable husky:

```
% HUSKY=0 npm install
npm WARN skipping integrity check for git dependency ssh://git@github.com/lifion/lifion-kinesis.git 
npm ERR! code 1
npm ERR! path $WORKSPACE/node_modules/lifion-kinesis
npm ERR! command failed
npm ERR! command sh -c -- husky install
npm ERR! .git can't be found (see https://git.io/Jc3F9)
```

**Comment by shiftj18** [comment]
![image](https://github.com/typicode/husky/assets/8348072/35244013-9985-43d9-a2fe-0cc7e90fa3e4)

![image](https://github.com/typicode/husky/assets/8348072/a525b427-1237-42e9-8224-b20dc6513a88)


> husky/lib/index.js
```js
function install(dir = '.husky') {
    if (process.env.HUSKY === '0') {
        l('HUSKY env variable is set to 0, skipping install');
        return;
    }
    if (git(['rev-parse']).status !== 0) {
        l(`git command not found, skipping install`);
        return;
    }
    const url = 'https://typicode.github.io/husky/#/?id=custom-directory';
    if (!p.resolve(process.cwd(), dir).startsWith(process.cwd())) {
        throw new Error(`.. not allowed (see ${url})`);
    }
    if (!fs.existsSync('.git')) {
        throw new Error(`.git can't be found (see ${url})`);
    }
    try {
        fs.mkdirSync(p.join(dir, '_'), { recursive: true });
        fs.writeFileSync(p.join(dir, '_/.gitignore'), '*');
        fs.copyFileSync(p.join(__dirname, '../husky.sh'), p.join(dir, '_/husky.sh'));
        const { error } = git(['config', 'core.hooksPath', dir]);
        if (error) {
            throw error;
        }
    }
    catch (e) {
        l('Git hooks failed to install');
        throw e;
    }
    l('Git hooks installed');
}
```

So，the question maybe because the logic of `git command not found, skipping install` is not hit, where `.git` exists in the parent directory instead of the current directory.

So, the solution maybe is let `git rev-parse` just work in current directory, not searches upwards.

https://stackoverflow.com/questions/27177248/how-can-i-make-git-work-only-on-the-current-directory
https://stackoverflow.com/questions/2545602/how-to-git-ignore-subfolders-subdirectories

**Comment by Teng-Olive** [comment]
> > The case you may be in is if your package.json file and .git directory are not at the same level. For example, project/.git and project/front/package.json.
> > By design, husky install must be run in the same directory as .git, but you can change directory during prepare script and pass a subdirectory:
> > Change script in package.json to this: // package.json { "scripts": { "prepare": "cd .. && husky install front/.husky" } }
> > Then do npm install to fix it
> 
> Thanks it worked

>it work perfectly thank you

**Comment by bechar-ce** [comment]
Hi,

To generate .husky folder, we can approach the below line of code in the script tag for any nested project folder

"prepare": "cd ../../ && husky install .husky",

Regards,
-Bechar

**Comment by sunskyT** [comment]
> > The case you may be in is if your package.json file and .git directory are not at the same level. For example, project/.git and project/front/package.json.您可能遇到的情况是，如果您的 package.json 文件和 .git 目录不在同一级别。例如，project/.git 和project/front/package.json。
> > By design, husky install must be run in the same directory as .git, but you can change directory during prepare script and pass a subdirectory:根据设计，husky 安装必须在与 .git 相同的目录中运行，但您可以在准备脚本期间更改目录并传递子目录：
> > Change script in package.json to this: // package.json { "scripts": { "prepare": "cd .. && husky install front/.husky" } }将 package.json 中的脚本更改为： // package.json { "scripts": { "prepare": "cd .. && husky install front/.husky" } }
> > Then do npm install to fix it然后执行 npm install 来修复它
> 
> Thanks it worked 谢谢它成功了

yes！ it is effective，You helped a Chinese boy, and I can't find the relevant information on the Chinese website。

> > > The case you may be in is if your package.json file and .git directory are not at the same level. For example, project/.git and project/front/package.json.您可能遇到的情况是，如果您的 package.json 文件和 .git 目录不在同一级别。例如，project/.git 和project/front/package.json。
> > > By design, husky install must be run in the same directory as .git, but you can change directory during prepare script and pass a subdirectory:根据设计，husky 安装必须在与 .git 相同的目录中运行，但您可以在准备脚本期间更改目录并传递子目录：
> > > Change script in package.json to this: // package.json { "scripts": { "prepare": "cd .. && husky install front/.husky" } }将 package.json 中的脚本更改为： // package.json { "scripts": { "prepare": "cd .. && husky install front/.husky" } }
> > > Then do npm install to fix it然后执行 npm install 来修复它
> > 
> > 
> > Thanks it worked 谢谢它成功了
> 
> > it work perfectly thank you它工作完美，谢谢

yes！ it is effective，You helped a Chinese boy, and I can't find the relevant information on the Chinese website。

**Comment by its-dibo** [comment]
> Hi [@mondeja](https://github.com/mondeja),
> 
> Thanks for the report. It's fixed in `v5.0.9`. If not in a git repo, Git will simply output a message and not fail.

Does husky need .git to run even if .husky scripts exist?
as a use case when building a container using docker, I list `.git` in `.dockerignore` but keep `.husky`, when running `install` I expect husky to run

**Comment by sunskyT** [comment]
Subject: Re: [typicode/husky] 'husky install' fails if '.git' directory does not exist (#851)

Dear @mondeja,

Thank you for your prompt response and for fixing the issue in v5.0.9. I really appreciate your attention to this matter.

I encountered a similar issue in my project where the package.json file and the .git directory are not in the same directory. For example, the project structure looks like this:
go
复制编辑


project/   ├── .git/   ├── package.json   └── front/       └── package.json 


In this case, I realized that Husky's installation needs to be executed from the directory that contains the .git directory. To resolve this, I modified the prepare script in the package.json to adjust the working directory during installation:
json
复制编辑


{   "scripts": {     "prepare": "cd .. &amp;&amp; husky install front/.husky"   } } 


With this change, running npm install ensures that Husky is installed in the correct directory, and the .husky directory is properly set up.

Once again, thank you for your help, and I hope this solution can assist others facing a similar setup.

Best regards,
[sunsky]





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "typicode/husky"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月20日(星期一) 下午5:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [typicode/husky] 'husky install' fails if '.git' directory does not exists (#851)





  
Hi @mondeja,
 
Thanks for the report. It's fixed in v5.0.9. If not in a git repo, Git will simply output a message and not fail.
  
Does husky need .git to run even if .husky scripts exist?
 as a use case when building a container using docker, I list .git in .dockerignore but keep .husky, when running install I expect husky to run
